buy albums
wolox-training/jb-graphql pull request #12
Opened 2019-08-23 16:21 UTC by jonnyalexbh

## Summary
- buy albums

## Trello Card
https://trello.com/c/3RpHfhjV/15-comprar-albums

## Screenshot
<img width="1678" alt="Screen Shot 2019-08-23 at 11 20 51 AM" src="https://user-images.githubusercontent.com/9538756/63607438-1cc6c400-c598-11e9-92f9-128f302c095d.png">

2019-08-26 03:52 UTC, emanuelcasco requested changes

2019-08-26 03:52 UTC, emanuelcasco commented on app/graphql/albums/mutations.js
> +    buyAlbum: (_, params, context) => buyAlbum(_, params, context)
You can do: `{ mutations: { buyAlbum } }`
 _(pointfree)_

2019-08-27 20:23 UTC, emanuelcasco requested changes

2019-08-27 20:23 UTC, emanuelcasco commented on app/graphql/albums/resolvers.js
> +  }
Look up for graphql middleware to do this validation. You should noy pollute your resolvers with this logic. Take in mind that in real-word-projects you'll have to validate authentication in several resolvers, you cannot repeat this in each one

2019-08-27 20:23 UTC, emanuelcasco commented on app/models/purchase.js
> +  Purchase.createModel = buy => Purchase.findOrCreate({ where: buy, default: {} });
What happens if same user buys the same album several times?

2019-08-27 20:49 UTC, jonnyalexbh commented on app/models/purchase.js
> +  Purchase.createModel = buy => Purchase.findOrCreate({ where: buy, default: {} });
don't create one again `findOrCreate` the method will result in a respective instance. If the element does not yet exist, it will be created.

2019-08-27 20:55 UTC, emanuelcasco commented on app/models/purchase.js
> +  Purchase.createModel = buy => Purchase.findOrCreate({ where: buy, default: {} });
But you as user, would probably want to buy the same album again

2019-08-27 21:25 UTC, jonnyalexbh commented on app/models/purchase.js
> +  Purchase.createModel = buy => Purchase.findOrCreate({ where: buy, default: {} });
it is correct but the card requests `Un usuario no puede comprar 2 veces el mismo album.` https://trello.com/c/3RpHfhjV/15-comprar-albums  Do you think if I change it?

2019-08-28 12:33 UTC, emanuelcasco commented on app/models/purchase.js
> +  Purchase.createModel = buy => Purchase.findOrCreate({ where: buy, default: {} });
Ooh you are right, my bad!

2019-08-30 15:22 UTC, emanuelcasco requested changes

2019-08-30 15:22 UTC, emanuelcasco commented on app/graphql/albums/middleware.js
> +  return resolve(root, args, { user });
Be careful here. Imagine you save more information in the context, besides `user`, in that case this middleware will omit that information. Return the entire context please

2019-08-30 15:22 UTC, emanuelcasco commented on app/helpers.js
> +    throw errors.unauthorizedError('unauthorized token');
Add logs here

2019-08-30 15:22 UTC, emanuelcasco commented on app/services/purchase.js
> +        throw error.alreadyExistsError(`The user has already bought album with id ${buy.albumId}`);
Add logs please

2019-08-30 16:20 UTC, emanuelcasco commented on app/graphql/albums/resolvers.js
>    return tempAlbums.map(album => changeUserIdByArtist(album));
Just as a reminder you can use _pointfree style_: tempAlbums.map(changeUserIdByArtist)

2019-08-30 16:21 UTC, emanuelcasco approved these changes

2019-08-30 16:42 UTC, merged