Error format
wolox-training/jb-graphql pull request #9
Opened 2019-08-20 15:46 UTC by jonnyalexbh

## Summary
- error handling in GraphQL

## Trello Card
https://trello.com/c/cRweKkew/19-manejo-de-errores-en-graphql

## Screenshot
<img width="1680" alt="Screen Shot 2019-08-20 at 10 43 21 AM" src="https://user-images.githubusercontent.com/9538756/63362609-bc394c00-c337-11e9-9ee2-e7e2f48473fe.png">

2019-08-21 13:40 UTC, emanuelcasco requested changes

2019-08-21 13:40 UTC, emanuelcasco commented on server.js
> +      })
- Abstract `formatError` to a function, reference it here. 
- Make sure to log errors in the function.
- WRITE TEST! This is very important, you should write test for every new functionality.

2019-08-21 13:47 UTC, emanuelcasco requested changes

2019-08-21 13:47 UTC, emanuelcasco commented on server.js
> +      })
Also, make sure to catch errors in every service/resolver you are using. All errors should be catched and parsed before pass it to Apollo. For example:

- Return 404 when required resource is not available.
- Return 400 when input is invalid.
- Return 503 when database connection fails.
- And so on...

2019-08-26 19:11 UTC, emanuelcasco approved these changes

2019-08-26 19:12 UTC, emanuelcasco requested changes

2019-08-26 19:12 UTC, emanuelcasco commented on app/services/album.js
> +  error = require('../errors'),
Name it errors

2019-08-27 20:16 UTC, emanuelcasco requested changes

2019-08-27 20:16 UTC, emanuelcasco commented on server.js
> +      formatError: err => helpers.showError(err)
Replace for `formatError : helpers.showError`

2019-08-27 20:16 UTC, emanuelcasco commented on app/models/user.js
> +    });
Do you test this method? Where are you using it?

2019-08-28 15:14 UTC, jonnyalexbh commented on app/models/user.js
> +    });
this method was by default in the bootstrap

2019-08-29 18:54 UTC, emanuelcasco commented on app/models/user.js
> +    });
Ok, no problem. But take this in mind: https://blog.pragmatists.com/the-many-faces-of-this-in-javascript-5f8be40df52e

2019-08-29 18:56 UTC, emanuelcasco approved these changes
Great work here! 

![image](https://user-images.githubusercontent.com/4696005/63968199-800f9500-ca75-11e9-84be-1cf2b62aeb0d.png)

2019-08-29 18:56 UTC, merged